int led1 = 2;
int led2 = 3;
int led3 = 4;
int led4 = 5;
int led5 = 6;
int led6 = 7;
int led7 = 8;
int led8 = 9;
int led9 = 10;
int led10 = 11;

void chenille(){
   digitalWrite(led1,HIGH);
    delay(100);
    digitalWrite(led2,HIGH);
    delay(100);
    digitalWrite(led3,HIGH);
    delay(100);
    digitalWrite(led4,HIGH);
    delay(100);
    digitalWrite(led5,HIGH);
    delay(100);
    digitalWrite(led6,HIGH);
    delay(100);
    digitalWrite(led7,HIGH);
    delay(100);
    digitalWrite(led8,HIGH);
    delay(100);
    digitalWrite(led9,HIGH);
    delay(100);
    digitalWrite(led10,HIGH);
    delay(100);
    digitalWrite(led1,LOW);
    delay(100);
    digitalWrite(led2,LOW);
    delay(100);
    digitalWrite(led3,LOW);
    delay(100);
    digitalWrite(led4,LOW);
    delay(100);
    digitalWrite(led5,LOW);
    delay(100);
    digitalWrite(led6,LOW);
    delay(100);
    digitalWrite(led7,LOW);
    delay(100);
    digitalWrite(led8,LOW);
    delay(100);
    digitalWrite(led9,LOW);
    delay(100);
    digitalWrite(led10,LOW);
    delay(100);
}
void deuxSurDeux(){
  digitalWrite(led2,HIGH);
  digitalWrite(led4,HIGH);
  digitalWrite(led6,HIGH);
  digitalWrite(led8,HIGH);
  digitalWrite(led10,HIGH);
  digitalWrite(led1,LOW);
  delay(100);
  digitalWrite(led1,HIGH);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  digitalWrite(led5,LOW);
  delay(100);
  digitalWrite(led5,HIGH);
  digitalWrite(led7,LOW);
  delay(100);
  digitalWrite(led7,HIGH);
  digitalWrite(led9,LOW);
  delay(100);
  digitalWrite(led9,HIGH);
}

void troisSurTrois(){
  digitalWrite(led1,HIGH);
  digitalWrite(led2,HIGH);
  digitalWrite(led3,HIGH);
  digitalWrite(led4,HIGH);
  digitalWrite(led5,HIGH);
  digitalWrite(led6,HIGH);
  digitalWrite(led7,HIGH);
  digitalWrite(led8,HIGH);
  digitalWrite(led9,HIGH);
  digitalWrite(led10,HIGH);
  digitalWrite(led1,LOW);
  delay(250);
  digitalWrite(led1,HIGH);
  digitalWrite(led4,LOW);
  delay(250);
  digitalWrite(led4,HIGH);
  digitalWrite(led7,LOW);
  delay(250);
  digitalWrite(led7,HIGH);
  digitalWrite(led10,LOW);
  delay(250);
  digitalWrite(led10,HIGH);
  digitalWrite(led3,LOW);
  delay(250);
  digitalWrite(led3,HIGH);
  digitalWrite(led6,LOW);
  delay(250);
  digitalWrite(led6,HIGH);
  digitalWrite(led9,LOW);
  delay(250);
  digitalWrite(led9,HIGH);
  digitalWrite(led2,LOW);
  delay(250);
  digitalWrite(led2,HIGH);
  digitalWrite(led5,LOW);
  delay(250);
  digitalWrite(led5,HIGH);
  digitalWrite(led8,LOW);
  delay(250);
  digitalWrite(led8,HIGH);
}

void clignotant(){
    digitalWrite(led1,HIGH);
    digitalWrite(led2,HIGH);
    digitalWrite(led3,HIGH);
    digitalWrite(led4,HIGH);
    digitalWrite(led5,HIGH);
    digitalWrite(led6,HIGH);
    digitalWrite(led7,HIGH);
    digitalWrite(led8,HIGH);
    digitalWrite(led9,HIGH);
    digitalWrite(led10,HIGH);
    delay(200);
    digitalWrite(led1,LOW);
    digitalWrite(led2,LOW);
    digitalWrite(led3,LOW);
    digitalWrite(led4,LOW);
    digitalWrite(led5,LOW);
    digitalWrite(led6,LOW);
    digitalWrite(led7,LOW);
    digitalWrite(led8,LOW);
    digitalWrite(led9,LOW);
    digitalWrite(led10,LOW);
    delay(200);
}

void defaut(){
  digitalWrite(led1,HIGH);
  digitalWrite(led2,HIGH);
  digitalWrite(led3,HIGH);
  digitalWrite(led4,HIGH);
  digitalWrite(led5,HIGH);
  digitalWrite(led6,HIGH);
  digitalWrite(led7,HIGH);
  digitalWrite(led8,HIGH);
  digitalWrite(led9,HIGH);
  digitalWrite(led10,HIGH);
}
